[package]
name = "mtge-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.31.0"
image = "0.24.1"
nalgebra-glm = "0.16.0"
rayon = "1.5.1"

[features]
